In [13]:
from tensorflow.keras.preprocessing.text import one_hot

In [14]:
sent = ['the glass of milk', 
        'the glass of juice',
        'the cup of tea',
        'I am a good guy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good', 
        ]

In [15]:
voc_size = 10000


In [16]:
one_hot_repr = [one_hot(words, voc_size)for words in sent]
one_hot_repr


[[910, 212, 661, 2406],
 [910, 212, 661, 822],
 [910, 4209, 661, 2742],
 [1326, 9775, 7060, 7815, 8812],
 [1326, 9775, 7060, 7815, 2431],
 [5099, 910, 975, 661, 1922],
 [1791, 3179, 1930, 7815]]

In [17]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np


In [18]:
sent_length=8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  910  212  661 2406]
 [   0    0    0    0  910  212  661  822]
 [   0    0    0    0  910 4209  661 2742]
 [   0    0    0 1326 9775 7060 7815 8812]
 [   0    0    0 1326 9775 7060 7815 2431]
 [   0    0    0 5099  910  975  661 1922]
 [   0    0    0    0 1791 3179 1930 7815]]


In [19]:
dim = 10 


In [24]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

# Initialize the model
model = Sequential()

# Add only the Embedding layer
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_length))

model.build(input_shape=(None, 8))

model.compile(optimizer='adam', loss='binary_crossentropy')

# Print the model summary
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)